sources:
  bundler: true

allowed:
  - 'mit'
  - 'apache-2.0'
  - 'cc0-1.0'
  - 'isc'
  - 'bsd-2-clause'
  - 'bsd-3-clause'

reviewed:
  bundler:
    - 'activerecord'
    - 'activerecord-nulldb-adapter'
    - 'concurrent-ruby'
    - 'ffi'
    - 'method_source'
    - 'nokogiri'
    - 'pg'
    - 'pg_query'
    - 'puma'
    - 'rack'
    - 'tilt'
    - 'websocket-driver'
    - 'websocket-extensions'
