name: standardrb

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  standardrb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: run standardrb
        run: bundle exec standardrb
